/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfcheckout.gui;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import selfcheckout.mysql.MySQLConn;

/**
 *
 * @author Matt
 */
public class RemoveProductGUI extends javax.swing.JFrame {

    /**
     * Creates new form RemoveProductGUI
     */
    
    String product;
    
    MySQLConn connect = new MySQLConn();
    Connection conn = null;
    
    GridLayout searchLayout;

    public RemoveProductGUI() {
        initComponents();
        
        searchLayout = new GridLayout(0,4);
        
        //Set the GridLayout as the layout for the panel
        jPanel1.setLayout(searchLayout);
        
        //Adjust the horizontal and vertical gaps between buttons
        searchLayout.setHgap(10);
        searchLayout.setVgap(10);
        
        //Preferred Size of the buttons
        JButton b = new JButton("Just a fake button");
        Dimension buttonSize = b.getPreferredSize();
        jPanel1.setPreferredSize(new Dimension((int)(buttonSize.getWidth() * 3.5) + 10,
            (int)(buttonSize.getHeight() * 3.5) + 10 * 2));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 98, 181, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 95, -1, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 424, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 138, -1, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Product to Remove");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, 645, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        product = searchTextField.getText();
        jPanel1.removeAll();
        DisplayItems();
        jPanel1.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

   public void DisplayItems()
    {
        //Number of rows for the result set
        int rows = 0;
        try
        {
            //Connect and open the connection to the DB
            conn = connect.DBUtils();
            
            //Create the query and the result set to get the results
            String query = "SELECT * FROM SelfCheckOut.Products WHERE Name LIKE ?";
            PreparedStatement stmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stmt.setString(1, "%" + product + "%");
            ResultSet rs = stmt.executeQuery();
            rs.next();

            //Find the number of rows
            if(rs.last())
            {
                rows = rs.getRow();
                //Move the cursor to the beginning
                rs.beforeFirst();
            }

            //Create Buttons for each product that matches the search word
            for(int i = 0; i < rows; i++)
            {
                if(rs.next() != false)
                {
                    String name = rs.getString("Name");
                    JButton button = new JButton(name);
                    button.addActionListener(deleteItem);
                    jPanel1.add(button);
                }
            }

        }catch (Exception ex)
        {
            Logger.getLogger(SearchResultGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private ActionListener deleteItem = new ActionListener()
    {
         public void actionPerformed(ActionEvent e)
         {
             String value = e.getActionCommand();
             try
             {
                conn = connect.DBUtils();
                Statement statement = conn.createStatement();
                String query = "DELETE FROM SelfCheckOut.Products WHERE Name = ?";
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString(1, value);
                
                preparedStmt.execute();
                
                conn.close();
                jPanel1.setVisible(false);
             }
             catch (Exception ex)
             {
                Logger.getLogger(ProductGUI.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         }
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveProductGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
